import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — BuildBlueprint AI" },
      { name: "description", content: "Terms of Service for BuildBlueprint AI." },
      { property: "og:title", content: "Terms of Service — BuildBlueprint AI" },
      { property: "og:url", content: "https://blueprint-genius-ai-88.lovable.app/terms" },
    ],
    links: [{ rel: "canonical", href: "https://blueprint-genius-ai-88.lovable.app/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <Link to="/" className="text-sm text-muted-foreground hover:text-foreground">← Home</Link>
      <h1 className="mt-6 font-display text-4xl font-semibold">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: June 2026</p>

      <div className="prose prose-invert mt-8 max-w-none space-y-5 text-sm leading-relaxed text-muted-foreground">
        <p><strong className="text-foreground">1. Acceptance.</strong> By creating an account or using BuildBlueprint AI ("the Service"), you agree to these Terms.</p>
        <p><strong className="text-foreground">2. The Service.</strong> The Service generates AI-assisted product blueprints, prompts, and related artifacts based on text you provide. Output is generated by third-party large language models and is provided as-is.</p>
        <p><strong className="text-foreground">3. Your account.</strong> You are responsible for activity under your account and for the accuracy of the information you provide.</p>
        <p><strong className="text-foreground">4. Acceptable use.</strong> No illegal, abusive, or infringing content. No attempts to reverse-engineer, scrape, or overload the Service. No use to build a directly competing product.</p>
        <p><strong className="text-foreground">5. Plans &amp; billing.</strong> Paid plans renew monthly until cancelled. Fees are non-refundable except where required by law. Quotas reset on the first of each month.</p>
        <p><strong className="text-foreground">6. Intellectual property.</strong> You own the ideas you submit and the blueprints generated from them. We retain rights to the Service software and brand.</p>
        <p><strong className="text-foreground">7. Warranties &amp; liability.</strong> The Service is provided "as is" without warranty of any kind. To the maximum extent permitted by law, our aggregate liability is limited to fees paid in the prior 12 months.</p>
        <p><strong className="text-foreground">8. Termination.</strong> Either party may terminate at any time. We may suspend accounts that violate these Terms.</p>
        <p><strong className="text-foreground">9. Changes.</strong> We may update these Terms; material changes will be announced in-app.</p>
        <p><strong className="text-foreground">10. Contact.</strong> support@buildblueprint.ai</p>
      </div>
    </main>
  );
}
